
name: bash-lint

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Step 1 - Install ShellCheck
        run: sudo apt install shellcheck -y

      - name: Step 2 - Lint script k8s_profile.sh
        run: shellcheck k8s_profile.sh

      - name: Step 2 - Lint script aws_profile.sh
        run: shellcheck aws_profile.sh
